---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 80, host: 80}]
    - ["forwarded_port", {guest: 443, host: 443}]


provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - build-essential
      - jenkins::master
      - jenkins-configuration
      - apache-configuration::jenkins-reverseproxy
    attributes:
      jenkins_git:
        username: jenkins_git_user
        email: jenkins@nowhere.com
      jenkins:
        version: "1.598"
        install_method: package
        cert_subject: "/CN=www.somebody.com/O=someorg/C=US/ST=MD/L=somecity"
        server:
          plugins:
            - name: scripttrigger
              version: "0.28"
        http_proxy:
          ssl:
            enabled: true
            redirect_http: true
            cert_path: /etc/httpd/ssl/server.crt
            key_path: /etc/httpd/ssl/server.key

        global_vars:
          region: us-east-1



