---
driver:
  name: vagrant
  network:
    - ["forwarded_port", {guest: 8080, host: 8080}]
    - ["forwarded_port", {guest: 8443, host: 8443}]


provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - build-essential
      - jenkins::master
      - apache-configuration::jenkins-reverseproxy
      - jenkins-configuration
    attributes:
      apache:
        listen_ports:
          - '8080'
      jenkins_git:
        username: jenkins_git_user
        email: jenkins@nowhere.com
      jenkins:
        version: "1.598"
        install_method: package
        master:
          port: 9090
        server:
          plugins:
            - name: scripttrigger
              version: '0.28'
            - name: email-ext
              version: '2.35.1'
        http_proxy:
          host_name: localhost
          listen_port: 8080
        global_vars:
          region: us-east-1
          domain: dummyjenkins.com
        email:
          username: ses_user
          secret_key: ses_secret_key
          admin_email_address: admin@dummyjenkins.com
          smtp_server: email-smtp.us-east-1.amazonaws.com
          smtp_port: '587'
          jenkins_url: http://localhost:8080

      jenkins_security:
        authz_strategy: none

  - name: secure
    run_list:
      - build-essential
      - jenkins::master
      - apache-configuration::jenkins-reverseproxy
      - jenkins-configuration
    attributes:
      apache:
        listen_ports:
          - '8080'
          - '8443'
      jenkins_git:
        username: jenkins_git_user
        email: jenkins@nowhere.com
      jenkins:
        version: "1.598"
        install_method: package
        cert_subject: "/CN=www.somebody.com/O=someorg/C=US/ST=MD/L=somecity"
        master:
          port: 9090
        server:
          plugins:
            - name: scripttrigger
              version: '0.28'
        http_proxy:
          host_name: localhost
          listen_port: 8080
          ssl:
            enabled: true
            redirect_http: true
            cert_path: /etc/httpd/ssl/server.crt
            key_path: /etc/httpd/ssl/server.key
            listen_port: 8443

        global_vars:
          region: us-east-1
      jenkins_security:
        authz_strategy: matrix

